// <auto-generated />
namespace JobPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Jobs_Location_Dates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jobs_Location_Dates));
        
        string IMigrationMetadata.Id
        {
            get { return "202304192111180_Jobs_Location_Dates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
