// <auto-generated />
namespace JobPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Database_correction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Database_correction));
        
        string IMigrationMetadata.Id
        {
            get { return "202304222123064_Database_correction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
